name: Deploy Terraform
on: 
  push:
    paths: 
      - '**.tf'
      - '.github/workflows/ci-infra.yml'
permissions:
  contents: read
  packages: read
  pull-requests: write
  
jobs:
  validate-terraform-plan:
    env:
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Infrastructure/
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform fmt
        run: terraform fmt
        
      - name: Terraform validate
        run: terraform validate 

      - name: Terraform fmt check
        run: terraform fmt -check -recursive  
        
      - name: Terraform Plan
        run: terraform plan 
        
  pre_deploy_security_checks:
      needs: validate-terraform-plan
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: Infrastructure/
      steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  
  
      - name: Run Checkov Security Scan
        id: checkov
        uses: bridgecrewio/checkov-action@v4
        with:
          directory: Infrastructure/
          framework: terraform
          output_format: cli
          soft_fail: true
          quiet: true

        
